(define-constant API-KEY "")
(define-constant USERNAME "")
(define-constant USER-ID 123456789)
(define-constant MY-COLLAGE-ID 123456789)
(define-constant BASE-URI "")
(define-constant INDEX-URI (string-append BASE-URI ""))
(define-constant SNATCHED-URI (string-append BASE-URI ""))
(define-constant GROUP-URI (string-append BASE-URI ""))
(define-constant COLLAGE-URI (string-append BASE-URI ""))
(define-constant NBR-OF-SNATCHES 123456789)
(define-constant API-HOST "")
(define-constant API-PATH "")
(define-constant API-SNATCHED-ACTION "")
(define-constant EXPECTED-SNATCHED-URI "")
(define-constant EXPECTED-GROUP-URI-WITH-ID-1234 "")
(define-constant EXPECTED-IMAGE-URI-WITH-ID-1234 "")

(define-constant PAOGARDEN-PATH "")
(define-constant TIDDLERS-PATH (string-append PAOGARDEN-PATH ""))
(define-constant EXISTING-RECORDS (string-append PAOGARDEN-PATH ""))
(define-constant TEST-IMAGE-URI "")
